INSERT INTO CLUB(NAME) VALUES('DINAMO ZAGREB');
INSERT INTO CLUB(NAME) VALUES('HNK RIJEKA');
INSERT INTO CLUB(NAME) VALUES('SLAVEN BELUPO');

INSERT INTO CHAMPIONSHIP(NAME, DESCRIPTION)
VALUES('SUPERSPORT HNL', 'SEZONA 2023/2024');

INSERT INTO CHAMPIONSHIP_CLUB(CHAMPIONSHIP_ID, CLUB_ID)
VALUES((SELECT ID FROM CHAMPIONSHIP WHERE NAME = 'SUPERSPORT HNL'),
        SELECT ID FROM CLUB WHERE NAME = 'DINAMO ZAGREB');

INSERT INTO CHAMPIONSHIP_CLUB(CHAMPIONSHIP_ID, CLUB_ID)
VALUES((SELECT ID FROM CHAMPIONSHIP WHERE NAME = 'SUPERSPORT HNL'),
          SELECT ID FROM CLUB WHERE NAME = 'HNK RIJEKA');

INSERT INTO CHAMPIONSHIP_CLUB(CHAMPIONSHIP_ID, CLUB_ID)
VALUES((SELECT ID FROM CHAMPIONSHIP WHERE NAME = 'SUPERSPORT HNL'),
          SELECT ID FROM CLUB WHERE NAME = 'SLAVEN BELUPO');

INSERT INTO USERS VALUES('user', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW', TRUE);
INSERT INTO USERS VALUES('admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW', TRUE);

INSERT INTO AUTHORITIES VALUES('user', 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES('admin', 'ROLE_ADMIN');

