CREATE TABLE CLUB (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);

CREATE TABLE CHAMPIONSHIP(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE CHAMPIONSHIP_CLUB(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CHAMPIONSHIP_ID INT NOT NULL,
    CLUB_ID INT NOT NULL,
    FOREIGN KEY(CHAMPIONSHIP_ID) REFERENCES CHAMPIONSHIP(ID),
    FOREIGN KEY(CLUB_ID) REFERENCES CLUB(ID)
);

CREATE TABLE USERS (
                       USERNAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
                       PASSWORD VARCHAR_IGNORECASE(100) NOT NULL,
                       ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
                             USERNAME VARCHAR_IGNORECASE(50) NOT NULL,
                             AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,
                             CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);
